[Interface]
PrivateKey=wJ9QVdYP1O8bYJzb+vCrWUCAihFQCKSQPJ7lMWP55Gc=
Address=172.21.6.140
DNS=23.82.141.129,23.82.141.131
[Peer]
PublicKey=dVjqUFtrXzgw9Qv38OVYuz6jan6g5z4VySpRJ0c7gXo=
AllowedIPs=0.0.0.0/0
Endpoint=sx0112202-ikev.dnsdialer.com:51820
PersistentKeepalive=21